In [1]:
import numpy as np
from scipy.linalg import solve

In [2]:
def f(x):
    return np.sin(x/5)*np.exp(x/10) + 5*np.exp(-x/2)

In [3]:
A = np.array([[1, 1], [15, 1]])
b = np.array([f(1), f(15)])

In [4]:
x = solve(A, b)

In [5]:
x

array([-0.18692825,  3.43914511])

In [6]:
A = np.array([[1, 1, 1], [1, 8, 64], [1, 15, 225]])
b = np.array([f(1), f(8), f(15)])

In [7]:
x = solve(A, b)

In [8]:
x

array([ 3.32512949, -0.06531159, -0.00760104])

In [9]:
A = np.array([[1,1,1,1], [1, 4, 16, 64], [1, 10, 100, 1000], [1, 15, 225, 3375]])
b = np.array([f(1), f(4), f(10), f(15)])

In [10]:
x = solve(A, b)

In [11]:
x

array([ 4.36264154, -1.29552587,  0.19333685, -0.00823565])

In [12]:
ans = ' '.join(str(k) for k in x)

In [13]:
ans

'4.36264153512 -1.29552586569 0.193336847022 -0.00823565117332'

In [14]:
outFile = open('submission-2.txt', 'w')
outFile.write(ans)
outFile.close()